//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCPSLSettingChanger.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ScreenResolutionChoice {
            get {
                return ((int)(this["ScreenResolutionChoice"]));
            }
            set {
                this["ScreenResolutionChoice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int WindowModeChoice {
            get {
                return ((int)(this["WindowModeChoice"]));
            }
            set {
                this["WindowModeChoice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool VSyncEnabled {
            get {
                return ((bool)(this["VSyncEnabled"]));
            }
            set {
                this["VSyncEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int FPSLimitChoice {
            get {
                return ((int)(this["FPSLimitChoice"]));
            }
            set {
                this["FPSLimitChoice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TextureQualityChoice {
            get {
                return ((int)(this["TextureQualityChoice"]));
            }
            set {
                this["TextureQualityChoice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MaxBloodAmountChoice {
            get {
                return ((int)(this["MaxBloodAmountChoice"]));
            }
            set {
                this["MaxBloodAmountChoice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShadowsEnabled {
            get {
                return ((bool)(this["ShadowsEnabled"]));
            }
            set {
                this["ShadowsEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ShadowResolutionChoice {
            get {
                return ((int)(this["ShadowResolutionChoice"]));
            }
            set {
                this["ShadowResolutionChoice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ShadowDistanceChoice {
            get {
                return ((int)(this["ShadowDistanceChoice"]));
            }
            set {
                this["ShadowDistanceChoice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MotionBlurEnabled {
            get {
                return ((bool)(this["MotionBlurEnabled"]));
            }
            set {
                this["MotionBlurEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ColorCorrectionEnabled {
            get {
                return ((bool)(this["ColorCorrectionEnabled"]));
            }
            set {
                this["ColorCorrectionEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AntiAliasingEnabled {
            get {
                return ((bool)(this["AntiAliasingEnabled"]));
            }
            set {
                this["AntiAliasingEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LightRenderingModeEnabled {
            get {
                return ((bool)(this["LightRenderingModeEnabled"]));
            }
            set {
                this["LightRenderingModeEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double MasterVolumeValue {
            get {
                return ((double)(this["MasterVolumeValue"]));
            }
            set {
                this["MasterVolumeValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double SoundEffectsVolumeValue {
            get {
                return ((double)(this["SoundEffectsVolumeValue"]));
            }
            set {
                this["SoundEffectsVolumeValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double VoiceChatVolumeValue {
            get {
                return ((double)(this["VoiceChatVolumeValue"]));
            }
            set {
                this["VoiceChatVolumeValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double MenuMusicVolumeValue {
            get {
                return ((double)(this["MenuMusicVolumeValue"]));
            }
            set {
                this["MenuMusicVolumeValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double InterfaceVolumeValue {
            get {
                return ((double)(this["InterfaceVolumeValue"]));
            }
            set {
                this["InterfaceVolumeValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SameMenuMusicAndInterfaceVolumeValueEnabled {
            get {
                return ((bool)(this["SameMenuMusicAndInterfaceVolumeValueEnabled"]));
            }
            set {
                this["SameMenuMusicAndInterfaceVolumeValueEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MenuThemeChoice {
            get {
                return ((int)(this["MenuThemeChoice"]));
            }
            set {
                this["MenuThemeChoice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int LanguageChoice {
            get {
                return ((int)(this["LanguageChoice"]));
            }
            set {
                this["LanguageChoice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int MainMenuChoice {
            get {
                return ((int)(this["MainMenuChoice"]));
            }
            set {
                this["MainMenuChoice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DisplaySteamProfileEnabled {
            get {
                return ((bool)(this["DisplaySteamProfileEnabled"]));
            }
            set {
                this["DisplaySteamProfileEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DoNotTrackEnabled {
            get {
                return ((bool)(this["DoNotTrackEnabled"]));
            }
            set {
                this["DoNotTrackEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FastIntroFadeEnabled {
            get {
                return ((bool)(this["FastIntroFadeEnabled"]));
            }
            set {
                this["FastIntroFadeEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HeadBobEnabled {
            get {
                return ((bool)(this["HeadBobEnabled"]));
            }
            set {
                this["HeadBobEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ToggleSprintEnabled {
            get {
                return ((bool)(this["ToggleSprintEnabled"]));
            }
            set {
                this["ToggleSprintEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DisplayExactHPValueEnabled {
            get {
                return ((bool)(this["DisplayExactHPValueEnabled"]));
            }
            set {
                this["DisplayExactHPValueEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RichPresenceEnabled {
            get {
                return ((bool)(this["RichPresenceEnabled"]));
            }
            set {
                this["RichPresenceEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PublicLobbyEnabled {
            get {
                return ((bool)(this["PublicLobbyEnabled"]));
            }
            set {
                this["PublicLobbyEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HideIPEnabled {
            get {
                return ((bool)(this["HideIPEnabled"]));
            }
            set {
                this["HideIPEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ToggleSearchEnabled {
            get {
                return ((bool)(this["ToggleSearchEnabled"]));
            }
            set {
                this["ToggleSearchEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SCP079ToggleViewEnabled {
            get {
                return ((bool)(this["SCP079ToggleViewEnabled"]));
            }
            set {
                this["SCP079ToggleViewEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SCP079EnablePostProcessingEnabled {
            get {
                return ((bool)(this["SCP079EnablePostProcessingEnabled"]));
            }
            set {
                this["SCP079EnablePostProcessingEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double BrightnessValue {
            get {
                return ((double)(this["BrightnessValue"]));
            }
            set {
                this["BrightnessValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double SensitivityValue {
            get {
                return ((double)(this["SensitivityValue"]));
            }
            set {
                this["SensitivityValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InvertYAxisEnabled {
            get {
                return ((bool)(this["InvertYAxisEnabled"]));
            }
            set {
                this["InvertYAxisEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int E11SightChoice {
            get {
                return ((int)(this["E11SightChoice"]));
            }
            set {
                this["E11SightChoice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int E11BarrelChoice {
            get {
                return ((int)(this["E11BarrelChoice"]));
            }
            set {
                this["E11BarrelChoice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int E11OtherChoice {
            get {
                return ((int)(this["E11OtherChoice"]));
            }
            set {
                this["E11OtherChoice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Project90SightChoice {
            get {
                return ((int)(this["Project90SightChoice"]));
            }
            set {
                this["Project90SightChoice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Project90BarrelChoice {
            get {
                return ((int)(this["Project90BarrelChoice"]));
            }
            set {
                this["Project90BarrelChoice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Project90OtherChoice {
            get {
                return ((int)(this["Project90OtherChoice"]));
            }
            set {
                this["Project90OtherChoice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MP7SightChoice {
            get {
                return ((int)(this["MP7SightChoice"]));
            }
            set {
                this["MP7SightChoice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MP7BarrelChoice {
            get {
                return ((int)(this["MP7BarrelChoice"]));
            }
            set {
                this["MP7BarrelChoice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MP7OtherChoice {
            get {
                return ((int)(this["MP7OtherChoice"]));
            }
            set {
                this["MP7OtherChoice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int USPSightChoice {
            get {
                return ((int)(this["USPSightChoice"]));
            }
            set {
                this["USPSightChoice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int USPBarrelChoice {
            get {
                return ((int)(this["USPBarrelChoice"]));
            }
            set {
                this["USPBarrelChoice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int USPOtherChoice {
            get {
                return ((int)(this["USPOtherChoice"]));
            }
            set {
                this["USPOtherChoice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int COM15SightChoice {
            get {
                return ((int)(this["COM15SightChoice"]));
            }
            set {
                this["COM15SightChoice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int COM15BarrelChoice {
            get {
                return ((int)(this["COM15BarrelChoice"]));
            }
            set {
                this["COM15BarrelChoice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int COM15OtherChoice {
            get {
                return ((int)(this["COM15OtherChoice"]));
            }
            set {
                this["COM15OtherChoice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int GraphicsAPIChoice {
            get {
                return ((int)(this["GraphicsAPIChoice"]));
            }
            set {
                this["GraphicsAPIChoice"] = value;
            }
        }
    }
}
